### ISSUE TITLE
puku doesn't work with `./pleasew`

### ISSUE THREAD

**Issue by manfredlift** [please-build/puku#133]
I am installing puku as a please tool as per the readme:
```toml
[Alias "puku"]
Cmd = run //third_party/binary:puku --
PositionalLabels = true
Desc = A tool to update BUILD files in Go packages 
```

When trying to puku sync it complains about not finding `plz`.
```console
$ ./pleasew puku sync -w
15:21:58 CRITICAL failed to query config: %!w(*errors.errorString=&{exec: "plz": executable file not found in $PATH
})
```

I believe `./pleasew` installs it in `~/.please` with the name `please` so there's no chance for puku to ever find it even if the $PATH gets set correctly?
